version: '3.9'
services:
  reactapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ReactDevContainer
    volumes:
      - .:/usr/src
    # command: sh -c "npm start"
    ports:
      - "3000:3000"
    stdin_open: true
